- action:
  - service: script.set_nest_away
  - data:
      entity_id: switch.smart_plug_isp6x
    service: homeassistant.turn_off
  alias: Going Away
  condition: []
  id: '1517789781995'
  trigger:
  - entity_id: group.all_devices
    from: home
    platform: state
    to: not_home
- action:
  - service: script.set_nest_home
  alias: Return Home (Nest)
  condition: []
  id: '1517789810662'
  trigger:
  - entity_id: group.all_devices
    from: not_home
    platform: state
    to: home
- action:
  - data:
      entity_id: switch.smart_plug_isp6x
    service: homeassistant.turn_on
  alias: Lights At Sunset
  condition:
  - condition: state
    entity_id: group.all_devices
    state: home
  id: '1517793421956'
  trigger:
  - event: sunset
    platform: sun
- action:
  - data:
      entity_id: switch.smart_plug_isp6x
    service: homeassistant.turn_on
  alias: Returning home after dark
  condition:
  - after: sunset
    condition: sun
  id: '1517794860921'
  trigger:
  - entity_id: group.all_devices
    from: not_home
    platform: state
    to: home
- action:
  - data:
      entity_id: switch.smart_plug_isp6x
    service: homeassistant.turn_off
  - data:
      entity_id: switch.sonoff_strip
    service: homeassistant.turn_off
  alias: Lights Out - Bed Time
  condition:
  - after: '23:00:00'
    before: 06:00:00
    condition: time
  id: '1517802312064'
  trigger:
  - entity_id: media_player.chromecast_jason
    platform: state
    to: playing
- action:
  - service: script.set_nest_home
  alias: Nest Home Enforcement
  condition:
  - condition: state
    entity_id: group.all_devices
    state: home
  id: '1518315692254'
  trigger:
  - entity_id: sensor.living_room_thermostat_operation_mode
    from: heat
    platform: state
    to: eco
- action:
  - data:
      data:
        actions:
        - action: open
          icon: /static/icons/favicon-192x192.png
          title: Open Home Assistant
        - action: set_nest_home
          tag: notification-away-check
          title: Reset Status
      message: Did you leave home?
      title: Home Assistant
    service: notify.gcm_esssentialph1
  alias: Test Notification
  condition: []
  id: '1518408606916'
  trigger:
  - entity_id: group.all_devices
    from: home
    platform: state
    to: not_home
- action:
  - service: script.set_nest_away
  alias: Nest Away Enforcememt
  condition:
  - condition: state
    entity_id: group.all_devices
    state: not_home
  id: '1518531142193'
  trigger:
  - entity_id: sensor.living_room_thermostat_operation_mode
    from: eco
    platform: state
    to: heat
- alias: Kitchen Strip Animation Speed
  initial_state: true
  hide_entity: false
  trigger:
  - platform: state
    entity_id: input_number.kitchen_animation_speed
  action:
  - service: mqtt.publish
    data_template:
      topic: home/mqttstrip/set
      payload: '{"transition":{{ trigger.to_state.state | int }}}'
- action:
  - service: script.discord_spam
  alias: TIMMIE TENDIE TIME
  condition: []
  id: '1519348964028'
  trigger:
  - entity_id: sensor.timthetatman
    from: offline
    platform: state
    to: streaming

# - alias: Weekly Backup at 3 AM
  # trigger:
    # platform: time
    # at: '3:00:00'
  # condition:
  # - condition: time
    # weekday:
    # - mon
  # action:
  # - service: hassio.snapshot_full
    # data_template:
      # name: Automated Backup {{ now().strftime('%Y-%m-%d') }}
  # - service: notify.slack_notify
    # data_template:
      # message: Creating backup named "Automated Backup {{ now().strftime('%Y-%m-%d')
  # - delay: '02:00:00'
  # - service: hassio.addon_stdin
    # data_template:
      # addon: 7be23ff5_dropbox_sync
      # input:
        # command: upload